# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/volt-x-climate-web',
                'doc_host': 'https://arnos-stuff.github.io',
                'git_url': 'https://github.com/arnos-stuff/volt-x-climate-web',
                'lib_path': 'volt_x_climate_web'},
  'syms': {'volt_x_climate_web.core': {'volt_x_climate_web.core.foo': ('core.html#foo', 'volt_x_climate_web/core.py')}}}
